# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5234d4e1e3bbfc71a8ed46ddcc0229c12065beb4676e3332f8758debc849ede9c8d3934dba827224d59c914567addd53ca84e7a0b5780bc49b163b73a8ce8b

test:
  secret_key_base: 9edf131d5fbe2fb8bcea35fd7031c95f21f39457a800dd3bca923862a4ca3e34ea5e60a96463fe52bfdb48240d93a4045f9e3e726ce3d9a4bee2338ff4f3d598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
